### ISSUE TITLE
Errors in console?

### ISSUE THREAD

**Issue by erikmellum** [airshiphq/airship-js#22]
I am integrating airship-js into our ember application. We have a test flag set up. 
```
await Airship.configure({
  envKey: 'envKey',
});
await Airship.identify({ id: '1234' });
const flag = Airship.flag('test-flag');
const testFlagEnabled = flag.isEnabled();
console.log('test flag is: ' + testFlag ? 'enabled' : 'disabled');
```
-> Outputs `test flag is: enabled`

We get some console errors:

`Unexpected flag type encountered`

`OPTIONS https://api.airshiphq.com/v2/identify/gs3uo2eun0x0x5xi 405`

`Failed to load https://api.airshiphq.com/v2/identify/gs3uo2eun0x0x5xi: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.`

`Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.`

`https://api.airshiphq.com/v2/identify/gs3uo2eun0x0x5xi 405`

`Failed to load https://api.airshiphq.com/v2/identify/gs3uo2eun0x0x5xi: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.`

![image](https://user-images.githubusercontent.com/6475033/45905994-58b14200-bda7-11e8-973f-2a7e2b3307bb.png)

It's unclear if I'm the one causing the errors, or what is going on. Any ideas?

**Comment by glusa8** [comment]
Looking into it now! Thanks for reporting.

**Comment by erikmellum** [comment]
Sure thing, let me know if you need any additional information.

**Comment by glusa8** [comment]
@erikmellum , it should be fixed now. Let me know if there is any issues still. I'll close this Issue at the end of the day.

**Comment by erikmellum** [comment]
@glusa8 indeed, it does look fixed overall. I'm still getting the Unexpected flag type error though.

![image](https://user-images.githubusercontent.com/6475033/45906967-f8240400-bdaa-11e8-8105-0ce7f4e05b8d.png)


Perhaps this one is user error?

**Comment by glusa8** [comment]
@erikmellum , fixed that issue as well. Sorry about that. Let me know if you encounter other issues.

**Comment by erikmellum** [comment]
Looks good to me. Thanks for the incredibly fast responses and fix!
